<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PromosiSeeder extends Seeder
{
    public function run()
    {
        DB::table('promosi')->insert([
            [
                'id_penduduk' => 1,
                'nama_usaha' => 'Usaha 1',
                'gambar' => 'gambar1.jpg',
                'deskripsi' => 'Deskripsi usaha 1',
                'kategori' => 'Kuliner',
                'status_pengajuan' => 'Terima',
                'alamat' => 'Alamat usaha 1',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 2,
                'nama_usaha' => 'Usaha 2',
                'gambar' => 'gambar2.jpg',
                'deskripsi' => 'Deskripsi usaha 2',
                'kategori' => 'Fashion',
                'status_pengajuan' => 'Menunggu',
                'alamat' => 'Alamat usaha 2',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(15),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 3,
                'nama_usaha' => 'Usaha 3',
                'gambar' => 'gambar3.jpg',
                'deskripsi' => 'Deskripsi usaha 3',
                'kategori' => 'Retail',
                'status_pengajuan' => 'Tolak',
                'alamat' => 'Alamat usaha 3',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 4,
                'nama_usaha' => 'Usaha 4',
                'gambar' => 'gambar4.jpg',
                'deskripsi' => 'Deskripsi usaha 4',
                'kategori' => 'Jasa',
                'status_pengajuan' => 'Terima',
                'alamat' => 'Alamat usaha 4',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 5,
                'nama_usaha' => 'Usaha 5',
                'gambar' => 'gambar5.jpg',
                'deskripsi' => 'Deskripsi usaha 5',
                'kategori' => 'Lainnya',
                'status_pengajuan' => 'Menunggu',
                'alamat' => 'Alamat usaha 5',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(30),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 6,
                'nama_usaha' => 'Usaha 6',
                'gambar' => 'gambar6.jpg',
                'deskripsi' => 'Deskripsi usaha 6',
                'kategori' => 'Kuliner',
                'status_pengajuan' => 'Terima',
                'alamat' => 'Alamat usaha 6',
                'no_telp' => '1234567890',
                'countdown' => now()->subDays(1), // Countdown habis
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 7,
                'nama_usaha' => 'Usaha 7',
                'gambar' => 'gambar7.jpg',
                'deskripsi' => 'Deskripsi usaha 7',
                'kategori' => 'Fashion',
                'status_pengajuan' => 'Menunggu',
                'alamat' => 'Alamat usaha 7',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(5),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 8,
                'nama_usaha' => 'Usaha 8',
                'gambar' => 'gambar8.jpg',
                'deskripsi' => 'Deskripsi usaha 8',
                'kategori' => 'Retail',
                'status_pengajuan' => 'Tolak',
                'alamat' => 'Alamat usaha 8',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(10),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 9,
                'nama_usaha' => 'Usaha 9',
                'gambar' => 'gambar9.jpg',
                'deskripsi' => 'Deskripsi usaha 9',
                'kategori' => 'Jasa',
                'status_pengajuan' => 'Terima',
                'alamat' => 'Alamat usaha 9',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(15),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'id_penduduk' => 10,
                'nama_usaha' => 'Usaha 10',
                'gambar' => 'gambar10.jpg',
                'deskripsi' => 'Deskripsi usaha 10',
                'kategori' => 'Lainnya',
                'status_pengajuan' => 'Menunggu',
                'alamat' => 'Alamat usaha 10',
                'no_telp' => '1234567890',
                'countdown' => now()->addDays(20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
